### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by AGrosserHH** [amiratag/ACE#1]
Hi, 
I am trying to run the file ace_run.py with 

python3 ace_run.py --num_parallel_runs 0 --target_class Zebra --source_dir ./source ---working_dir ./save --model_to_run InceptionV3 --bottlenecks mixed_8 --num_test 20 --num_random_exp 40 --max_imgs 50 --min_imgs 30 --test_dir ./test
but I am getting an error message:

Traceback (most recent call last):
  File "ace_run.py", line 11, in <module>
    import ace_helpers
  File "/home/andi/Git/ACE/ace_helpers.py", line 8, in <module>
    import model
ModuleNotFoundError: No module named 'model'

Is there a file missing?

Cheers,
Andi

**Comment by tabularML** [comment]
Thanks a lot! The issue is fixed!
