### ISSUE TITLE
what's the random500 directory?

### ISSUE THREAD

**Issue by wodsoe** [amiratag/ACE#3]
Hi,what's the random500 directory?
Could you upload all files and directories?

**Comment by tabularML** [comment]
Hi, thanks for your great question! I updated the read me file to explain what random 500 folders are for. (basically, for instance if you set num_random_exp=20, you need to create folders random500_0, rando500_1, ..., random_500_20 where each folder contains a set of 500 randomly selected images of the dataset (ImageNet in our case))

**Comment by wodsoe** [comment]
OK!
Thank you!
