### ISSUE TITLE
modulenotfound

### ISSUE THREAD

**Issue by justcho5** [amiratag/ACE#4]
Hi,
I didn't know how to contact the owner of this repository so I will submit some bugs I have run into so far.

Will you be updating the code to make it compatible with tf 2.0?

Also, in the description for running ace, there's a typo. 1) I think the file to run is ace_run.py and 2) I think ---working_dir is supposed to be --working_dir and -bottlenecks to --bottlenecks.

I'm going to be using this tool for my project with histology slides. I've also never posted issues, so I hope this is the right place to bring some bugs to your attention.

Thank you!

**Comment by tabularML** [comment]
Hi Justina, thanks for the typos! This is exactly the right place to ask any issues. For the bugs or any other feature you add to the code (e.g. making it compatible with tf2) you can submit a pull request and I can then merge it into the codebase.

**Comment by justcho5** [comment]
Great thanks! I am still working on getting it to work with my slides but I think it would be really awesome to use your tool in understanding and gaining insight into my deep learning model and pathology predictions. Hope I can get it to work!
