### ISSUE TITLE
Using the Xception model

### ISSUE THREAD

**Issue by justcho5** [amiratag/ACE#7]
Can this method be used with the Xception model? I'm trying to write a wrapper for it but I'm not sure about what the bottleneck layers are.. I can get all the tensors from graph.get_operations() but I'm not sure how to determine which tensors would represent the bottleneck layers. If you have any suggestions, that would be great.

**Comment by tabularML** [comment]
Hi! I'm not familiar with this model but if you refer to the original paper that describes it it should be clear which are the bottleneck layers.
