### ISSUE TITLE
save_dir subdirectory explanations?

### ISSUE THREAD

**Issue by justcho5** [amiratag/ACE#9]
I did a small test with some random images and was wondering if you had some explanations for the directories within save_dir. In addition the annotations on the save_dir/results/*.png images (images are annotated with some numbers..). This would be really helpful to understand the results!

Thank you

**Comment by tabularML** [comment]
Aha thanks for asking. The images are basically the discovered concepts' examples (segments of original images that belong to that concept). The numbering is just an index.

**Comment by justcho5** [comment]
Does the numbering then refer to which concept it is? Are the images split to rows to signify some group? Sorry I'm still a bit confused. As an example, the following image is one row from the results folder. A few numbers (indexes) are repeated. Does the row of images mean something and what does  the index refer to?
<img width="580" alt="Screen Shot 2019-11-14 at 15 05 15" src="https://user-images.githubusercontent.com/19522811/68896029-363b6000-06f0-11ea-8e7c-f0b2eb2b4db3.png">

**Comment by justcho5** [comment]
I think I understand that each row represents a concept, but what does the index refer to?

**Comment by tabularML** [comment]
- So every row stands for a concept (a row of image pairs). 

- The number is the index of the original discovery image the concept is extracted from. (If you look again, for both of your examples where '1' is printed, the original image is the same)

-In each row, for each image pair, the image on the top is the extracted concept while the image on the bottom is the original image the concept is extracted from (shown by the yellow boundary). For instance:

![image](https://user-images.githubusercontent.com/26075007/69162948-42357200-0aa2-11ea-9982-3511db5c3418.png)
